stages:
  - build
  - test

build-apee-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/ape-vy-docker
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f base.dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - docker-build


test-contracts:
  stage: test
  image: docker:latest
  script:
    - docker pull $CI_REGISTRY_IMAGE/ape-vy-docker
    - docker build -t ape-vy-docker .
    - docker run --rm -v $PWD:/usr/src ape-vy-docker ape test
  only:
    - main

