stages:
  - build
  - test

build-brownie-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/electora-docker
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f base.dockerfile -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - docker-build

test-contracts:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/electora-docker
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker build -t electora-brownie .
    - docker run --rm -v $PWD:/usr/src electora-brownie brownie test
  only:
    - main
