stages:
  - test

test-contracts:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: electora-docker
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -f base.dockerfile -t ape-vy-docker .
    - docker run --rm -v $PWD:/usr/src ape-vy-docker ape test -v
  only:
    - main
